### ISSUE TITLE
장소 선정에 '영상촬영 유의사항'을 넣어보고 싶습니다.

### ISSUE THREAD

**Issue by samslow** [KMU-OSS-Laboratory/Hackathon-Manual#8]
안녕하세요. 해커톤들을 다니면서 이번 오픈핵 2018 처럼 완성도 있는 해커톤을 처음 경험하고 오픈소스에 대해 새로운 경험을 얻게 된 참가자입니다. 이전에 '멋쟁이 사자처럼'에서 행사를 일정 부분 기획하게 될 일이 있었는데 그때도 이런 문서가 있었으면 참 좋았겠다라는 생각이 들어 혹 이후 다른 어떤 사람에게라도 도움이 될까싶어 Issue를 남겨봅니다. 

저는 개발자이기 이전에 영상을 취미로 하는 학생이었습니다.
이번 해커톤 내용에 영상촬영과 관련된 내용들은 따로 다루지 않아 4~5개 정도의 아이디어톤과 해커톤을 다니며 촬영한 경험과 시행착오를 간단하게나마 함께 나누고자 합니다.

예를들어 'Google Campus'같은 경우 행사 이전에 사전 협의를 통해 촬영 허가를 받지 않으면 행사장 촬영이 굉장히 제한적으로 적용됩니다. 구캠측에 미리 말하고 협의만 했더라면 더 자유로운 구도로 촬영 할 수 있었을텐데 이를 알지못해 촬영을 제한적으로 할 수 밖에 없었습니다. 

이와 같은 내용을 전체적인 맥락을 고려하여 '장소선정' 목차에 한켠을 할애하여 넣으면 어떨까요?

넣을 내용을 요약하면 이렇습니다.
1. 영상 촬영을 하게 될 행사일 경우, 해당 장소에서 촬영을 해도 된다는 허가가 필요 할 수도 있으므로 협의가 필요하다.
2. 참가자 양식에서 개인정보 활용에 동의할 뿐 아니라 본인 얼굴이 나와도 상관 없다는 촬영 동의가 필요하다.
3. 행사 규모가 크다면 영상 스탭들이 행사장내에서 배터리교환, 렌즈교환 등을 자유롭게 할 수 있는 접근성있고 참가자들이 올 수 없는(비싼 장비들이 있기 때문) 공간이 필요하다.

생각나는 것 위주로 적었습니다.
영상으로 남기는 행사는 이후 행사가 4회 5회로 넘어감에따라 사람들이 참고 할 수 있는 중요한 기록물이라고 생각하므로 이런 메뉴얼에서 꼭한번쯤은 다뤄야 한다고 생각합니다 !

**Comment by minsuklee** [comment]
오 고맙습니다.
반영하겠습니다.

—
이민석
http://hl1itj.tistory.com


켜짐 2018년 9월 25일 에서 20:35:04, Hyeonseok (notifications@github.com) 작성됨:

안녕하세요. 해커톤들을 다니면서 이번 오픈핵 2018 처럼 완성도 있는 해커톤을 경험하고 오픈소스에 대해 새로운 경험을 얻게 된
참가자입니다. 이전에 '멋쟁이 사자처럼'에서 행사를 일정 부분 기획하게 될 일이 있었는데 그때도 이런 문서가 있었으면 참 좋았겠다라는
생각이 들어 혹 이후 다른 어떤 사람에게라도 도움이 될까싶어 Issue를 남겨봅니다.

저는 개발자이기 이전에 영상을 취미로 하는 학생이었습니다.
이번 해커톤 내용에 영상촬영과 관련된 내용들은 따로 다루지 않아 4~5개 정도의 아이디어톤과 해커톤을 다니며 촬영한 경험과 시행착오를
간단하게나마 함께 나누고자 합니다.

예를들어 'Google Campus'같은 경우 행사 이전에 사전 협의를 통해 촬영 허가를 받지 않으면 행사장 촬영이 굉장히 제한적으로
적용됩니다. 구캠측에 미리 말하고 협의만 했더라면 더 자유로운 구도로 촬영 할 수 있었을텐데 이를 알지못해 촬영을 제한적으로 할 수
밖에 없었습니다.

이와 같은 내용을 전체적인 맥락에 비교해 봤을때 '장소선정' 목차에 한켠을 할애하여 넣으면 어떨까요?

넣을 내용을 요약하면 이렇습니다.

   1. 영상 촬영을 하게 될 행사일 경우, 해당 장소에서 촬영을 해도 된다는 허가가 필요 할 수도 있으므로 협의가 필요하다.
   2. 개인정보 활용에 동의할 뿐 아니라 본인 얼굴이 나와도 상관 없다는 촬영 동의가 필요하다.
   3. 행사 규모가 크다면 영상 스탭들이 행사장내에서 배터리교환, 렌즈교환 등을 자유롭게 할 수 있는 접근성있고 참가자들이 올 수
   없는(비싼 장비들이 있기 때문) 공간이 필요하다.

생각나는 것 위주로 적었습니다.
영상으로 남기는 행사는 이후 행사가 4회 5회로 넘어감에따라 사람들이 참고 할 수 있는 중요한 기록물이라고 생각하므로 이런 메뉴얼에서
꼭한번쯤은 다뤄야 한다고 생각합니다 !

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KMU-OSS-Laboratory/Hackathon-Manual/issues/8>, or mute
the thread
